INSERT INTO users VALUES (1, 1000, 'user1@gmail.com', 'User 1', '1234')
INSERT INTO users VALUES (2, 1000, 'user2@gmail.com', 'User 2', '1234')
INSERT INTO users VALUES (3, 1000, 'user3@gmail.com', 'User 3', '1234')
INSERT INTO projects VALUES (1, 200,CURRENT_TIMESTAMP , 'This is unofficial project.', 'pathtoimage', 'ProjectTransformers', 500, 1, 2 )
INSERT INTO projects VALUES (2, 200,CURRENT_TIMESTAMP , 'This is unofficial project.', 'pathtoimage', 'ProjectGoogle', 500, 1, 2 )
INSERT INTO projects VALUES (3, 200,CURRENT_TIMESTAMP , 'This is unofficial project.', 'pathtoimage', 'ProjectAmazon', 500, 1, 3 )
INSERT INTO projects VALUES (4, 200,CURRENT_TIMESTAMP , 'This is unofficial project.', 'pathtoimage', 'ProjectMicrosoft', 500, 1, 1 )
INSERT INTO projects VALUES (5, 200,CURRENT_TIMESTAMP , 'This is unofficial project.', 'pathtoimage', 'ProjectGame', 500, 1, 2 )
INSERT INTO projects VALUES (6, 200,CURRENT_TIMESTAMP , 'This is unofficial project.', 'pathtoimage', 'ProjectUnreal', 500, 1, 1 )
INSERT INTO projects VALUES (7, 200,CURRENT_TIMESTAMP , 'This is unofficial project.', 'pathtoimage', 'ProjectLinkedin', 500, 1, 3 )
INSERT INTO projects VALUES (8, 200,CURRENT_TIMESTAMP , 'This is unofficial project.', 'pathtoimage', 'ProjectZamunda', 500, 1, 1 )

INSERT INTO pledges VALUES (1, 200, CURRENT_TIMESTAMP, 1, 1)
